author: SpleefLeague
authors: [NickM13]
description: SpleefLeague SuperJump Plugin
main: com.spleefleague.superjump.SuperJump
name: SuperJump
url: http://www.spleefleague.com/
version: 1.0
api-version: 1.13
softdepend: [ProtocolLib]