author: SpleefLeague
authors: [NickM13]
description: SpleefLeague Zones Plugin
main: com.spleefleague.zone.CoreZones
name: CoreZones
url: http://www.spleefleague.com/
version: 1.0
api-version: 1.13
softdepend:  [ Core, ProtocolLib ]
